[build]
  command = "node build-noop.js"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/scrape"
  to = "/.netlify/functions/scrape"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = 'none'

